# Outputting
lsi: false
safe: true
source: www 
permalink : /:title:output_ext
paginate: 12
paginate_path: /stories/latest/page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll-archives  
  # - jekyll-minifier

whitelist:
  - jekyll-paginate
    
# Archives
# jekyll-archives:
#   enabled:
#    - categories
#  layout: archive
#  permalinks:
#    category: '/:name/'
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Minification
# jekyll-minifier:
#   exclude: 'feed.xml'
    
# Other
markdown: kramdown
highlighter: rouge
future: false
sass:
  style: compact # possible values: nested expanded compact compressed
